package routes

import (
	"fmt"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/labstack/echo/v4"
	echoMw "github.com/labstack/echo/v4/middleware"
	creatorV1 "github.com/ystv/web-api/controllers/v1/creator"
	encoderV1 "github.com/ystv/web-api/controllers/v1/encoder"
	peopleV1 "github.com/ystv/web-api/controllers/v1/people"
	publicV1 "github.com/ystv/web-api/controllers/v1/public"
	streamV1 "github.com/ystv/web-api/controllers/v1/stream"
	_ "github.com/ystv/web-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/ystv/web-api/middleware"
	"github.com/ystv/web-api/utils"

	echoSwagger "github.com/swaggo/echo-swagger"
)

// TODO standarise on function names

// Init initialise routes
func Init(version, commit string) *echo.Echo {
	e := echo.New()
	e.HideBanner = true
	debug, err := strconv.ParseBool(os.Getenv("debug"))
	if err != nil {
		panic(err)
	}
	e.Debug = debug

	middleware.Init(e)
	config := echoMw.JWTConfig{
		Claims:      &utils.JWTClaims{},
		TokenLookup: "cookie:token",
		SigningKey:  []byte(os.Getenv("signing_key")),
	}

	// swagger
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.GET("/routes", func(c echo.Context) error {
		return c.JSON(http.StatusOK, e.Routes())
	})
	// ping
	e.GET("/ping", func(c echo.Context) error {
		resp := map[string]time.Time{"pong": time.Now()}
		return c.JSON(http.StatusOK, resp)
	})

	apiV1 := e.Group("v1")
	{
		internal := apiV1.Group("/internal")
		// Service web endpoints
		encoder := internal.Group("/encoder")
		{
			encoder.POST("/upload_request", encoderV1.VideoNew)
		}
		stream := internal.Group("/stream")
		{
			stream.POST("/auth", streamV1.CheckAuth)
		}
		// Internal user endpoints
		if !debug {
			internal.Use(echoMw.JWTWithConfig(config))
		}
		{
			people := internal.Group("/people")
			{
				people.GET("/user/full", peopleV1.UserByTokenFull)
				people.GET("/user/:id", peopleV1.UserByID)
				people.GET("/user/:id/full", peopleV1.UserByIDFull)
				people.GET("/user", peopleV1.UserByToken)
			}
			creator := internal.Group("/creator")
			{
				videos := creator.Group("/videos")
				{
					videos.GET("", creatorV1.VideoList)
					videos.GET("/my", creatorV1.VideosUser)
					videos.POST("", creatorV1.VideoNew)
					videoItem := videos.Group("/:id")
					{
						videoItem.GET("", creatorV1.VideoFind)
						videoItem.PUT("", notImplemented)
					}
				}
				series := creator.Group("/series")
				{
					series.GET("", creatorV1.SeriesListAll)
				}
				playlists := creator.Group("/playlists")
				{
					playlists.GET("", creatorV1.PlaylistAll)
					playlists.POST("", creatorV1.PlaylistNew)
					playlist := playlists.Group("/:id")
					{
						playlist.GET("", creatorV1.PlaylistGet)
						playlist.PUT("", notImplemented)
						playlist.DELETE("", notImplemented)
					}
				}
				encodes := creator.Group("/encodes")
				{
					profiles := encodes.Group("/profiles")
					{
						profiles.GET("", creatorV1.EncodeProfileList)
					}
				}
				creator.GET("/calendar/:year/:month", creatorV1.CalendarList)
				creator.GET("/stats", creatorV1.Stats)
			}
		}
		public := apiV1.Group("/public")
		{
			public.GET("/find/*", publicV1.Find)
			public.GET("/videos/:offset/:page", publicV1.ListVideos)
			public.GET("/video/:id", publicV1.Video)
			public.GET("/video/:id/breadcrumb", publicV1.VideoBreadcrumb)
			public.GET("/video/by_url", publicV1.URLToVideo)
			public.GET("/series/:id", publicV1.SeriesByID)
			public.GET("/series/:id/breadcrumb", publicV1.SeriesBreadcrumb)
			public.GET("/teams", publicV1.ListTeams)
			stream.GET("", publicV1.StreamList)
		}

	}
	e.GET("/", func(c echo.Context) error {
		text := fmt.Sprintf(`                                                                                
                                                              @@@@@             
                                                                     @@@@       
                                                                         @@@    
                                               @@@@                        @@@@ 
                                               @@@@                          @@@
        .    @@@@@         @@@@   @@@@@@     @@@@@@@@@  @@@@        @@@@     @@@
     @@       @@@@@       @@@@  @@@@@@@@@@   @@@@@@@@@   @@@@      @@@@       @@
   @@           @@@@    @@@@@   @@@@           @@@@       @@@@    @@@@       @@ 
  @@             @@@@  @@@@@     @@@@@@@@      @@@@        @@@@  @@@@       @@  
 @@               @@@@@@@@           @@@@@@    @@@@         @@@@@@@@      @@    
 @@@               @@@@@@       @@@    @@@@    @@@@          @@@@@@     @       
 @@@                @@@@        @@@@@@@@@@     @@@@           @@@@              
  (@@@             @@@@                                                         
     @@@         @@@@@          web-api                                         
        @@@@    @@@@@           Version: %s                                     
              @@@@@             Commit ID: %s                                                
`, version, commit)
		return c.String(http.StatusOK, text)
	})
	return e
}

func notImplemented(c echo.Context) error {
	return c.NoContent(http.StatusNotImplemented)
}
