-- +goose Up

CREATE SCHEMA IF NOT EXISTS mail;

create table mail.lists
(
    list_id       integer generated by default as identity
        primary key,
    name          text                  not null
        constraint namechk
            check (char_length(name) <= 20),
    description   text default ''::text not null,
    alias         text                  not null,
    permission_id integer
        references people.permissions
);

comment on table mail.lists is 'Mailing lists where you send to the alias and each subscriber receiver a copy';

create table mail.subscribers
(
    list_id      integer                         not null
        references mail.lists,
    user_id      integer                         not null
        references people.users,
    subscribe_id uuid default uuid_generate_v4() not null,
    primary key (user_id, subscribe_id)
);

comment on table mail.subscribers is 'Relationship of users subscribing to mailing lists';

comment on column mail.subscribers.subscribe_id is 'Using extra unique key since it will be used to unsubscribe from mailing lists
where the user doesn''t need to be signed-in';

-- +goose Down

DROP SCHEMA mail CASCADE;