-- +goose Up

CREATE SCHEMA IF NOT EXISTS misc;

create table misc.quotes
(
    quote_id    integer generated by default as identity
        primary key,
    quote       text                                   not null,
    description text                                   not null,
    created_at  timestamp with time zone default now() not null,
    created_by  integer
        references people.users
);

create table misc.webcams
(
    camera_id     integer generated by default as identity
        primary key,
    name          text                  not null
        constraint namechk
            check (char_length(name) <= 20),
    url           text                  not null,
    file          text                  not null,
    mime_type     text                  not null,
    enabled       boolean default false not null,
    permission_id integer
        references people.permissions
);

create table misc.teaching_periods
(
    period_id integer generated by default as identity
        primary key,
    year      integer                  not null,
    name      text                     not null
        constraint peroidchk
            check (name = ANY (ARRAY ['autumn'::text, 'spring'::text, 'summer'::text])),
    start     timestamp with time zone not null,
    finish    timestamp with time zone not null,
    constraint datechk
        check (finish > start)
);

comment on column misc.teaching_periods.finish is 'Midnight UTC, Monday Week 11';

create table misc.redirects
(
    redirect_id     integer generated by default as identity
        primary key,
    source_url      text not null
        unique,
    destination_url text not null,
    external        boolean default false
);

comment on column misc.redirects.destination_url is 'URL path by default it is not external and just internal,
can be made external with the external flag';

-- +goose Down

DROP SCHEMA misc CASCADE;