-- +goose Up

CREATE SCHEMA IF NOT EXISTS playout;
CREATE TABLE IF NOT EXISTS playout.channel
(
    channel_id      integer generated by default as identity
        primary key,
    url_name        text                     not null
        unique,
    name            text                     not null
        constraint name_chk
            check (char_length(name) <= 50),
    description     text                     not null,
    thumbnail       text                     not null,
    output_type     text                     not null
        constraint output_type_chk
            check (output_type = ANY (ARRAY ['hls'::text, 'iframe'::text])),
    output_url      text                     not null,
    visibility      text                     not null
        constraint visibility_chk
            check (visibility = ANY (ARRAY ['public'::text, 'internal'::text, 'unlisted'::text])),
    status          text                     not null
        constraint status_chk
            check (status = ANY (ARRAY ['live'::text, 'scheduled'::text, 'cancelled'::text, 'finished'::text])),
    location        text                     not null,
    scheduled_start timestamp with time zone not null,
    scheduled_end   timestamp with time zone not null,
    constraint time_chk
        check (scheduled_end > scheduled_start)
);

-- +goose Down

DROP SCHEMA playout CASCADE;
