// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	VideoBoxes string
	VideoFiles string
	Videos     string
}{
	VideoBoxes: "video_boxes",
	VideoFiles: "video_files",
	Videos:     "videos",
}
